Commented out the event watcher because it was crashing startup.
Error was:

Exiting
LoadError: Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile

See https://stackoverflow.com/questions/38663706/loaderror-could-not-load-the-listen-gem-rails-5